// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/product-cards/AmazonStyle.tsx": () => import("../components/mockups/product-cards/AmazonStyle.tsx"),
  "./components/mockups/product-cards/SheinStyle.tsx": () => import("../components/mockups/product-cards/SheinStyle.tsx"),
  "./components/mockups/product-cards/TemuStyle.tsx": () => import("../components/mockups/product-cards/TemuStyle.tsx")
};
